/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.LarsonAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.LarsonBounceValue;
import com.ctre.phoenix6.signals.RGBWColor;
import com.ctre.phoenix6.controls.RainbowAnimation;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("driveTrainCANivore");
    private final CANdle m_candle = new CANdle(46, kCANBus);


    private String gameData = "";
    private boolean blueWonAuto = false;
    private double matchTime = 0;
    private double shiftTime = 0;
    private boolean ourHubActive = true;

    private final LarsonAnimation m_slot0Animation = new LarsonAnimation(8, 21)
        .withSlot(0)
        .withColor(new RGBWColor(57, 255, 150, 0))
        .withSize(3)
        .withBounceMode(LarsonBounceValue.Front)
        .withFrameRate(Hertz.of(20));

    private final RainbowAnimation m_slot1Animation = new RainbowAnimation(8,21)
        .withSlot(1)
        .withFrameRate(Hertz.of(20));

    public LEDSubsystem() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            if(!ourHubActive){
                m_candle.setControl(m_slot0Animation);
            }else{
                m_candle.setControl(m_slot1Animation);
            }
            
        });
    }

    public void displayMatchInfo() {
        matchTime = DriverStation.getMatchTime();

        gameData = DriverStation.getGameSpecificMessage();

        if (gameData.length() > 0) {
            if (gameData.length() > 0) {
                if (gameData.charAt(0) == 'R') blueWonAuto = false;
                if (gameData.charAt(0) == 'B') blueWonAuto = true;
            }
            if (matchTime > 130) {
                shiftTime = matchTime - 130;
                ourHubActive = true;
            } else if (matchTime > 105) {
                shiftTime = matchTime - 105;
                ourHubActive = !(isBlue() ^ blueWonAuto);
            } else if (matchTime > 80) {
                shiftTime = matchTime - 80;
                ourHubActive = !(isBlue() ^ blueWonAuto);
            } else if (matchTime > 55) {
                shiftTime = matchTime - 55;
                ourHubActive = !(isBlue() ^ blueWonAuto);
            } else if (matchTime > 30) {
                shiftTime = matchTime - 30;
                ourHubActive = !(isBlue() ^ blueWonAuto);
            } else {
                shiftTime = matchTime;
                ourHubActive = true;
            }

            SmartDashboard.putString ("# who won auto", gameData.length() < 1 ? "No Data" : blueWonAuto ? "Blue" : "Red");
            SmartDashboard.putNumber("# Shift Time", shiftTime);
            SmartDashboard.putBoolean("# our hub active", ourHubActive);
        }

    }

    private boolean isBlue() {
        return DriverStation.getAlliance().get() != DriverStation.Alliance.Red;
    }
}
